# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdInsight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('retrieve_time', models.DateTimeField()),
                ('campaign_name', models.CharField(max_length=1024)),
                ('campaign_id', models.IntegerField()),
                ('adset_name', models.CharField(max_length=1024)),
                ('adset_id', models.IntegerField()),
                ('ad_name', models.CharField(max_length=1024)),
                ('ad_id', models.IntegerField()),
                ('past_2d_cost', models.FloatField()),
                ('past_2d_install', models.FloatField()),
                ('past_2d_CPI', models.FloatField()),
                ('past_7d_cost', models.FloatField()),
                ('past_7d_install', models.FloatField()),
                ('past_7d_CPI', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdInsightSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction_json', models.CharField(max_length=1048576)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('rule_json', models.CharField(max_length=1048576)),
            ],
        ),
        migrations.CreateModel(
            name='RuleExecutionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=True)),
                ('execution_time', models.DateTimeField()),
                ('adinsight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_monitor.AdInsight')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_monitor.Rule')),
            ],
        ),
    ]
